### ISSUE TITLE
[Question / Feature Request] AFK players don't count towards sleep requirement

### ISSUE THREAD

**Issue by CatAndPaste** [MagnusHJensen/SimpleAFK#1]
# Feature request

Hello! Found your mod on Modrinth, and couldn't find it in description: does your mod make AFK players not count towards the requirement for sleep / skip a night? If not, would you consider to make it a feature. I think it would be a nice addition :3

**Comment by MagnusHJensen** [comment]
Hi @CatAndPaste.
What mod do you use to do the sleep count for skipping night?
I'll be more than happy to add this! :D

**Comment by MagnusHJensen** [comment]
I found out MC has that built in vanilla, so I went ahead and added it based on that.

You can find the new 1.20.1 version here: https://modrinth.com/mod/simpleafk/version/1.20.1-1.1.0
You can find the new 1.18.2 version here: https://modrinth.com/mod/simpleafk/version/1.18.2-1.1.0

I hope you enjoy it, feel free to come back with any bugs or suggestions :D

**Comment by CatAndPaste** [comment]
Thank you very much, great update! And yes, I use gamerule to alter the percentage of players required to skip a night. 

I had to do it (setting it to 50% which is not great, but was only available workaround) since there are some people that like to afk on their farms or factories while others just want to skip a night for easier travel / building. Since now we have the mod that removes AFK players from requirement (it's yours!), I can remove or at least raise this value. Yay!
