### ISSUE TITLE
1.19.2 support / release

### ISSUE THREAD

**Issue by aws0jam** [MagnusHJensen/SimpleAFK#4]
Hello!  I have a question about whether there will be a 1.19.2 release, as I would like to use this version.

**Comment by MagnusHJensen** [comment]
I will look into porting it to 1.19.2

**Comment by MagnusHJensen** [comment]
It's now released for game versions 1.19, 1.19.1 and 1.19.2 (they use the same file). 🎉
Modrinth download: https://modrinth.com/mod/simpleafk/version/1.19.2-1.1.0
Curseforge download: https://www.curseforge.com/minecraft/mc-mods/simpleafk/files/4866342
