### ISSUE TITLE
Error Loading Mod

### ISSUE THREAD

**Issue by Harvestminer** [MagnusHJensen/SimpleAFK#6]
# Bug report

## Describe the bug

When using version 1.1.1 of this mod, I get an error when I boot up Minecraft stating:
"Mod simpleafk requires minecraft 1.20 or above, and below 1.20.1. Currently, minecraft is 1.20.1"

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Download simpleafk-1.1.1.jar
2. Drag file into mods folder
3. Launch Minecraft
4. See error: "Mod simpleafk requires minecraft 1.20 or above, and below 1.20.1. Currently, minecraft is 1.20.1"

## Expected behavior

Minecraft to boot up with no errors.

## Screenshots

![image](https://github.com/MagnusHJensen/SimpleAFK/assets/20891246/ed2ff02c-ef97-4b25-8ed8-2a2268dab904)

## System information

- OS: Windows 10 (amd64) version 10.0
- Version of neo-forge: 1.20.1-47.1.101
- Version of simpleafk: 1.1.1

## Additional context

Crash Report:
[crash-2024-03-20_21.24.50-fml.txt](https://github.com/MagnusHJensen/SimpleAFK/files/14681009/crash-2024-03-20_21.24.50-fml.txt)

**Comment by MagnusHJensen** [comment]
My bad, should be fixed in 1.1.2
