### ISSUE TITLE
Disable messages

### ISSUE THREAD

**Issue by EastRane** [MagnusHJensen/SimpleAFK#7]
Imo all these "afkmessages" in chat should be disabled if server's owner wants to. I tried leaving this messages empty (like ""), but they just return to default but I don't want to send messages on every player beginning their AFK session xd. Thank you

**Comment by MagnusHJensen** [comment]
I will look into this, not sure when! :D

**Comment by MagnusHJensen** [comment]
Hi @EastRane 

I've now gone ahead and implemented this:

You can find the version with these new config options here:

## 1.18.2
- [Modrinth](https://modrinth.com/mod/simpleafk/version/1.18.2-1.2.0)
- [Curseforge](https://www.curseforge.com/minecraft/mc-mods/simpleafk/files/5508216)

## 1.19.2
- [Modrinth](https://modrinth.com/mod/simpleafk/version/1.19.2-1.2.0)
- [Curseforge](https://www.curseforge.com/minecraft/mc-mods/simpleafk/files/5508264)

## 1.20.1
- [Modrinth](https://modrinth.com/mod/simpleafk/version/1.20.1-1.2.0)
- [Curseforge](https://www.curseforge.com/minecraft/mc-mods/simpleafk/files/5508323)
